# Installation:


#### from pip:


*  <font color = 'darkblue'>pip</font> <font color = 'green'>install</font> EmuPBk 
                                           

#### from source:
                                          
        
Clone or Download from : https://github.com/himmng/EmuPBk.git

* using terminal - cd <font color = 'darkblue'>EmuPBk</font>

* <font color = 'darkblue'>python</font> setup.py <font color = 'green'>install</font> 
  
   



## <font color = 'darkblue'>EmuPBk comes with 2 main features</font>

* <font color='green'>It will calculate the powerspectrum or Bispectrum for already exisiting trained model at $\textbf{existing_models}$ directory, the model for powerspectrum has an accuracy of 99% , and all Bispectrum emulators are more than 96% accurate, these are trained over 1000 data sets of simulated powerspectrum and Bispectrums given the 3 astrophysical parameter of EoR (Nion,Rmfp,NoH or Mhalo_min).</font>
Which can be used to for the prediction of the Powespectrum or Bispectrum for given the parameters.



* Secondly, one can train their own new ANN models by providing the data(Powerspectrum or Bispectrum) and parameters to the ANNs. <font color='dark orange'>These ANNs are $\textbf{semi-functional}$ in the sense, that they have some hyperparameters fixed (e.g.: No. of layers, No. of neurons in each layer, etc.), however, there are many hyperparamters which can be changed during the ANN's training</font> 

## How to Use:



In [4]:
import numpy as np

### <font color ='darkblue'> Using the already existed models for the prediction of  EoR 21-cm Powerspectrum or Bispectrum</font>

In [7]:
from EmuPBk.EMUPBK import EMUPBK

In [21]:
# let us create a parameter array
params = np.random.rand(6,3)

# it is better to have a large number
params = params*1000

# rounding-off upto 2 decimals 
params = np.around(params,2)
params = params[0]

### EmuPBk class can be used as follows:

In [22]:
predict = EMUPBK()

### Predictions of Power spectrum given the parameters (Nion, Rmfp, NoH)

In [23]:
Pk_pred = predict.PK(params)
Pk_pred

array([[ 32.219597 ,   5.9253764, -10.451671 , -45.836132 , -90.48717  ,
        -31.666758 , -88.20124  ]], dtype=float32)

### <font color='dark orange'>Predictions of Bispectrum for different $K_1 = (0.2,0.3,1.5)Mpc^{-1}$ scale, given the parameters (Nion, Rmfp, NoH)</font>

In [31]:
Bk_pred02 = predict.BK02(params)
Bk_pred02

array([[ 3.20977187e+00,  4.16581917e+00, -3.02448571e-01,
        -9.67551708e-01,  4.82441282e+00,  9.77697968e-01,
         1.09349430e+00,  2.19611764e+00,  7.54688692e+00,
         3.50393891e+00,  6.15433121e+00,  5.05010271e+00,
        -2.15115118e+00,  1.45205033e+00,  1.75147033e+00,
         4.81007528e+00,  1.17837942e+00,  5.11756086e+00,
        -6.84962940e+00, -3.30537367e+00,  2.23253870e+00,
        -2.31509805e+00,  1.45391989e+00,  4.07911348e+00,
        -9.76929128e-01, -1.80286720e-01, -2.38450098e+00,
         9.06060934e-01,  3.64790845e+00,  3.00539422e+00,
         4.69527066e-01,  3.70970869e+00,  1.56941459e-01,
         2.66222334e+00, -2.51803207e+00,  6.91595495e-01,
         1.65549362e+00,  2.57229686e+00,  2.47888708e+00,
         2.57972908e+00,  5.68567944e+00,  1.25249922e+00,
         8.92230797e+00,  6.09600067e+00,  8.13510776e-01,
         6.08059216e+00, -6.65523171e-01, -1.20160496e+00,
        -2.90544081e+00, -3.93671489e+00,  2.25816417e+0

In [26]:
Bk_pred03 = predict.BK03(params)
Bk_pred03

array([[ 1.73433316e+00, -8.19036551e-03, -8.29979002e-01,
        -2.45284939e+00, -1.53473628e+00, -1.55967462e+00,
        -3.72671843e-01,  9.66431439e-01,  1.54065311e+00,
        -3.73792481e+00,  5.35359979e-01, -3.80854487e-01,
        -3.21729565e+00, -2.28623891e+00, -5.72559871e-02,
        -5.21466911e-01,  1.12303042e+00, -1.53083944e+00,
        -1.90085113e+00, -1.65746140e+00, -9.11459923e-01,
        -2.22426510e+00, -2.06762147e+00, -1.53243852e+00,
        -4.33640778e-01,  2.04515886e+00, -2.76125026e+00,
         6.69718802e-01,  1.16585112e+00, -3.81587124e+00,
        -1.25636661e+00, -1.68451715e+00, -2.60333347e+00,
        -5.94519198e-01, -8.45840275e-01, -1.84970748e+00,
         7.88910329e-01, -4.42937851e+00, -3.27328324e+00,
        -4.96635407e-01, -7.49767959e-01,  7.00366259e-01,
         6.17079318e-01,  1.01078773e+00,  1.33409810e+00,
         7.67922282e-01, -3.60470831e-01,  6.38523176e-02,
         4.92456198e-01, -2.71417141e+00,  1.97453725e+0

In [27]:
Bk_pred15 = predict.BK15(params)
Bk_pred15

array([[ 4.32962984e-01,  6.28841579e-01, -2.72874188e+00,
         2.60918069e+00,  1.81123066e+00,  4.78139019e+00,
        -1.20627713e+00, -7.90942669e-01,  5.12566757e+00,
        -2.99905807e-01,  4.94645643e+00,  4.62617254e+00,
         2.86711311e+00,  5.68841219e+00,  2.22806287e+00,
         3.75686026e+00,  2.82142329e+00,  5.75443327e-01,
         3.35285544e+00, -9.93709624e-01,  4.15861130e+00,
         4.49218941e+00,  1.56669283e+00,  2.44309694e-01,
         3.18324518e+00,  1.87172091e+00,  3.21970010e+00,
         3.69910479e-01,  4.89669514e+00, -8.82284045e-01,
        -1.95779920e-01,  4.90853930e+00,  4.17804432e+00,
         2.37677455e+00,  2.88116574e+00, -3.85431737e-01,
         4.62173891e+00, -7.47104168e-01,  1.70876169e+00,
        -1.44902980e+00, -3.52137637e+00,  2.23881769e+00,
        -1.93555522e+00,  3.20522237e+00,  3.37146878e+00,
         2.90380388e-01, -2.34665489e+00, -2.68468451e+00,
        -1.73090601e+00, -2.23690605e+00,  3.05636168e+0

In [32]:
Bk_pred15.shape,Bk_pred02.shape

((1, 550), (1, 550))

It calulates the Bispectrum for a whole traingle parameter space