In [2]:
import matplotlib.pyplot as plt
import numpy as np
import keras as ks
import cosmoHammer as cm

In [3]:
%ls

binary_data_1.5/  dTb15             lvac15.png                  params15
bk_norm15         hyperparam.ipynb  nbins15                     x_HI15
bk_un15           index             parameter_estimation.ipynb


In [4]:
Bk = np.loadtxt('bk_norm15')
params = np.loadtxt('params15')
ind = np.loadtxt('index')
nbins = np.loadtxt('nbins15')

In [5]:
Bk.shape, params.shape , ind.shape, nbins.shape

((1058, 550), (1058, 3), (18,), (1058, 550))

In [6]:
index = np.zeros(len(ind),dtype = int)
for i in range(len(ind)):
    index[i] = ind[i]
index


array([ 146,  833,  516,  204,  929,  223,  154,   42,   87,   10,  535,
        343,  525,  239,   37,  532,  966, 1043])

In [7]:
Bk_test = Bk[index]
params_test = params[index]
bins_test = nbins[index]

In [8]:
Bk_test.shape, params_test.shape, bins_test.shape

((18, 550), (18, 3), (18, 550))

In [9]:
params_test[0]

array([ 20.,  20., 500.])

In [15]:
x = np.eye(550,550)
x.shape

(550, 550)

In [16]:
a = Bk_test[0]/np.sqrt(bins_test[0])

In [17]:
a = a*x

In [18]:
B = Bk_test[0]
B = np.reshape(B, (1,550))
B.shape

(1, 550)

In [20]:
b = np.dot(B,a)
b.shape

(1, 550)

In [22]:
c = np.dot(b,B.T)

In [23]:
c

array([[2.35755907e+22]])

In [ ]:
Bk_model = ks.models.load_model('')

In [ ]:
def logL(Bk,cov):
    